---
- name: Update web servers
  hosts: website
  remote_user: root
#  vars:
#    content: welcome to Ilki Webinar
  tasks:
  - name: Ensure nginx is at the latest version
    apt:
      name: nginx
      state: latest
      update_cache: yes
  - name: push website content
    copy:
      content: "{{ content }}"
      dest: index.nginx-debian.html
