name: CI

# Controls when the workflow will run
on:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: Format & validate Terraform files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2
    - name: Setup Terraform 1.1.2
      uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec
      with:
        terraform_version: 1.1.2
    - name: Initialize Terraform working directory
      run: terraform init -no-color -backend=false
    - name: Validate the configuration files
      run: terraform validate -no-color
    - name: Check if all Terraform configuration files are in a canonical format
      run: terraform fmt -check -recursive -diff -no-color
